"""Estado inicial

Revision ID: 6efc010d6064
Revises: 
Create Date: 2025-10-18 12:54:53.720197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efc010d6064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'review_likes', 'games', ['review_game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_games', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_games', type_='foreignkey')
    op.drop_constraint(None, 'review_likes', type_='foreignkey')
    # ### end Alembic commands ###
